import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/LandingPage/Header"
import Footer from "@/components/LandingPage/Footer";

const torusPro = localFont({
  src: [
    {
      path: "/fonts/TorusPro-regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/TorusPro-bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-torus-pro",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={torusPro.className}>
  <body className="antialiased">
    {/* <Header/> */}
    {children}
    {/* <Footer/> */}
    </body>
</html>

  );
}
