import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/LandingPage/Header";
import Footer from "@/components/LandingPage/Footer";
const torusPro = localFont({
  src: [
    {
      path: "/fonts/TorusPro-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/TorusPro-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "/fonts/TorusPro-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-torus-pro",
  display: "swap",
});
const poppins = localFont({
  src: [
    { path: "/fonts/Poppins-Regular.ttf", weight: "400", style: "normal" },
    { path: "/fonts/Poppins-Medium.ttf", weight: "500", style: "normal" },
    { path: "/fonts/Poppins-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "/fonts/Poppins-Bold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.className} ${torusPro.className}`}>
      <body className="antialiased">
        {/* <Header/> */}
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
